import './styles.css'

const BASE = import.meta.env.BASE_URL
const DATA_FILES = ['vehicle','software','issues','guides','uk-watch','sources','actions','change-log','site-meta']
const state = { data:{}, route:'today', query:'', status:'all', confidence:'all', favouritesOnly:false }
const personal = {
  favourites:new Set(JSON.parse(localStorage.getItem('wilson-favourites')||'[]')),
  read:new Set(JSON.parse(localStorage.getItem('wilson-read')||'[]')),
  recent:JSON.parse(localStorage.getItem('wilson-recent')||'[]')
}
const routes = [
  ['today','⌂','Today'],['wilson','⚡','Wilson'],['software','⬆','Software'],['issues','!','Issues'],
  ['guides','▤','Guides'],['uk-watch','◎','UK Watch'],['knowledge','◇','Knowledge Base'],['sources','↗','Sources'],['settings','⚙','Settings']
]
const esc = value => String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
const fmtDate = iso => iso ? new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${iso}T12:00:00Z`)) : 'Not recorded'
const normalise = text => String(text??'').toLowerCase().replaceAll('license','licence')
const allRecords = () => DATA_FILES.flatMap(k => Array.isArray(state.data[k]) ? state.data[k].map(x=>({...x,_type:k})) : [])
const byId = id => allRecords().find(x=>x.id===id)
function save(){ localStorage.setItem('wilson-favourites',JSON.stringify([...personal.favourites]));localStorage.setItem('wilson-read',JSON.stringify([...personal.read]));localStorage.setItem('wilson-recent',JSON.stringify(personal.recent)) }
function navigate(route){ location.hash=route; state.route=route; render() }
function iconButton(id){return `<button class="tiny-btn favourite ${personal.favourites.has(id)?'active':''}" data-favourite="${esc(id)}" aria-label="${personal.favourites.has(id)?'Remove from':'Add to'} favourites" title="Favourite">★</button>`}
function badges(r){return `<div class="meta"><span class="badge ${r.status==='confirmed'||r.status==='resolved'?'good':r.status==='open'||r.status==='pending'?'warn':''}"><span class="dot"></span>${esc(r.status||'reference')}</span>${r.confidence?`<span class="badge">${esc(r.confidence)} confidence</span>`:''}${r.region?`<span class="badge">${esc(r.region)}</span>`:''}${r.lastUpdated?`<span class="badge">Updated ${fmtDate(r.lastUpdated)}</span>`:''}</div>`}
function record(r){const source=(r.sources||[]).map(id=>byId(id)).filter(Boolean);return `<article class="record" data-record="${esc(r.id)}"><div class="record-head"><div><h3>${esc(r.title||r.name)}</h3>${badges(r)}</div><div class="record-actions">${iconButton(r.id)}<button class="tiny-btn copy" data-copy="${esc(r.id)}" aria-label="Copy ${esc(r.title||r.name)}">⧉</button></div></div><details><summary>View details</summary><p class="body">${esc(r.summary||r.description||r.details||'')}</p>${source.length?`<p><strong>Sources:</strong> ${source.map(s=>`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title)}</a>`).join(', ')}</p>`:''}<small>First seen ${fmtDate(r.firstSeen||r.created)} · Last checked ${fmtDate(r.lastChecked)}</small></details></article>`}
function filtered(records){return records.filter(r=>{const hay=normalise([r.title,r.name,r.summary,r.description,r.details,r.tags?.join(' ')].join(' '));return (!state.query||hay.includes(normalise(state.query)))&&(state.status==='all'||r.status===state.status)&&(state.confidence==='all'||r.confidence===state.confidence)&&(!state.favouritesOnly||personal.favourites.has(r.id))&&!r.archived})}
function listPage(title,subtitle,records){const items=filtered(records);return `<div class="hero"><span class="eyebrow">Wilson Hub</span><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><div class="filters"><select id="statusFilter" aria-label="Filter by status"><option value="all">All statuses</option>${[...new Set(records.map(x=>x.status).filter(Boolean))].map(x=>`<option ${state.status===x?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="confidenceFilter" aria-label="Filter by confidence"><option value="all">All confidence</option>${['high','medium','low'].map(x=>`<option ${state.confidence===x?'selected':''}>${x}</option>`).join('')}</select><button id="favouritesFilter" aria-pressed="${state.favouritesOnly}">★ Favourites</button></div><div class="list">${items.length?items.map(record).join(''):`<div class="empty"><h2>No matching records</h2><p>Try clearing search or filters.</p></div>`}</div>`}
function today(){const v=state.data.vehicle[0],sw=state.data.software.find(x=>x.current),changes=state.data['change-log'].filter(x=>!x.archived).slice(0,4),actions=state.data.actions.filter(x=>x.status==='pending');return `<div class="hero-row"><div class="hero"><span class="eyebrow">Daily dashboard</span><h1>Good afternoon, Wilson.</h1><p>Your Model 3 knowledge base, software watch and practical next actions — kept in one calm place.</p></div><div class="date-chip">${new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</div></div><div class="grid"><section class="card wide"><span class="eyebrow kicker">Vehicle</span><h2>${esc(v.model)}</h2><p>${esc(v.colour)} · ${esc(v.interior)} · ${esc(v.wheels)}</p><div class="meta"><span class="badge good"><span class="dot"></span>${esc(v.status)}</span><span class="badge">Collected ${fmtDate(v.collectionDate)}</span><span class="badge">${esc(v.registrationMasked)}</span></div></section><section class="card"><span class="label">Current software</span><div class="metric">${esc(sw.version)}</div><p>${esc(sw.summary)}</p></section><section class="card"><span class="label">Open checks</span><div class="metric">${actions.length}</div><p>Practical items to confirm during normal use.</p></section><section class="card"><span class="label">Saved items</span><div class="metric">${personal.favourites.size}</div><p>Favourites stay on this device only.</p></section><section class="card"><span class="label">Last content check</span><div class="metric">${fmtDate(state.data['site-meta'].lastChecked).replace(/\s\d{4}$/,'')}</div><p>Facts are dated, never assumed permanently current.</p></section><section class="card full"><div class="section-title"><h2>Recently updated</h2><button class="tiny-btn" data-route="knowledge">View all</button></div><div class="list">${changes.map(record).join('')}</div></section></div>`}
function wilson(){return listPage('Wilson','Confirmed vehicle facts and personal setup, with public identifiers masked.',state.data.vehicle)}
function knowledge(){return listPage('Knowledge Base','Search across every guide, issue, software note and UK watch item.',allRecords().filter(x=>!['sources','site-meta','change-log'].includes(x._type)))}
function settings(){return `<div class="hero"><span class="eyebrow">Personalisation</span><h1>Settings</h1><p>These preferences are stored only in this browser.</p></div><div class="grid"><section class="card"><h2>Appearance</h2><p>Choose a comfortable theme.</p><button class="tiny-btn" id="themeToggle">Toggle light / dark</button></section><section class="card"><h2>Reading history</h2><p>${personal.read.size} read · ${personal.recent.length} recently viewed.</p><button class="tiny-btn" id="clearState">Clear personal state</button></section><section class="card"><h2>Data status</h2><p>Factual content is versioned in the public repository, not browser storage.</p><span class="badge good"><span class="dot"></span>Structured and validated</span></section></div>`}
function page(){switch(state.route){case'today':return today();case'wilson':return wilson();case'software':return listPage('Software','Wilson’s version history, settings and update watch.',state.data.software);case'issues':return listPage('Issues','Open questions, resolved faults and troubleshooting history.',state.data.issues);case'guides':return listPage('Guides','Practical care, driving, charging and ownership guidance.',state.data.guides);case'uk-watch':return listPage('UK Watch','Dated UK-relevant travel, charging and ownership notes.',state.data['uk-watch']);case'knowledge':return knowledge();case'sources':return listPage('Sources','The references behind Wilson Hub records.',state.data.sources);case'settings':return settings();default:return today()}}
function nav(){return routes.map(([id,ico,label])=>`<button data-route="${id}" class="${state.route===id?'active':''}" aria-current="${state.route===id?'page':'false'}"><span class="nav-icon">${ico}</span>${label}</button>`).join('')}
function render(){document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">W</div><div><strong>Wilson Hub</strong><small>Model 3 · UK</small></div></div><nav class="nav" aria-label="Main navigation">${nav()}</nav><div class="side-footer">Facts checked, dated and sourced.<br>Private identifiers masked.</div></aside><main class="main"><header class="topbar"><div class="search"><span>⌕</span><input id="globalSearch" value="${esc(state.query)}" placeholder="Search Wilson Hub…" aria-label="Search Wilson Hub"></div><button class="icon-btn" id="themeIcon" aria-label="Toggle colour theme">◐</button></header><div class="content" id="content" tabindex="-1">${page()}</div></main><nav class="bottom-nav" aria-label="Mobile navigation">${routes.slice(0,5).map(([id,ico,label])=>`<button data-route="${id}" class="${state.route===id?'active':''}"><span class="nav-icon">${ico}</span>${label}</button>`).join('')}</nav></div>`;bind()}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.append(el);setTimeout(()=>el.remove(),1800)}
function toggleTheme(){const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('wilson-theme',next)}
function bind(){document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));document.querySelector('#globalSearch')?.addEventListener('input',e=>{state.query=e.target.value;if(state.route==='today')state.route='knowledge';render();document.querySelector('#globalSearch')?.focus()});document.querySelector('#statusFilter')?.addEventListener('change',e=>{state.status=e.target.value;render()});document.querySelector('#confidenceFilter')?.addEventListener('change',e=>{state.confidence=e.target.value;render()});document.querySelector('#favouritesFilter')?.addEventListener('click',()=>{state.favouritesOnly=!state.favouritesOnly;render()});document.querySelectorAll('[data-favourite]').forEach(b=>b.addEventListener('click',()=>{personal.favourites.has(b.dataset.favourite)?personal.favourites.delete(b.dataset.favourite):personal.favourites.add(b.dataset.favourite);save();render()}));document.querySelectorAll('[data-record]').forEach(el=>el.querySelector('summary')?.addEventListener('click',()=>{const id=el.dataset.record;personal.read.add(id);personal.recent=[id,...personal.recent.filter(x=>x!==id)].slice(0,10);save()}));document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{const r=byId(b.dataset.copy);await navigator.clipboard.writeText(`${r.title||r.name}\n${r.summary||r.description||''}`);toast('Copied to clipboard')}));document.querySelector('#themeIcon')?.addEventListener('click',toggleTheme);document.querySelector('#themeToggle')?.addEventListener('click',()=>{toggleTheme();render()});document.querySelector('#clearState')?.addEventListener('click',()=>{personal.favourites.clear();personal.read.clear();personal.recent=[];save();render();toast('Personal state cleared')})}
async function init(){document.documentElement.dataset.theme=localStorage.getItem('wilson-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');await Promise.all(DATA_FILES.map(async name=>{const r=await fetch(`${BASE}data/${name}.json`);if(!r.ok)throw new Error(`Could not load ${name}`);state.data[name]=await r.json()}));state.route=location.hash.slice(1)||'today';addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'today';render()});render()}
init().catch(err=>{document.querySelector('#app').innerHTML=`<div class="empty"><h1>Wilson Hub could not load</h1><p>${esc(err.message)}</p></div>`})

export { normalise, filtered }
